### ISSUE TITLE
Data disappears after each restart

### ISSUE THREAD

**Issue by wxyhgk** [cyllab/CalcUS#16]
Every time I run bash start.sh, all my data disappears

**Comment by RaphaelRobidas** [comment]
Hello, thanks for reporting this issue. I will need some more information to figure out what could be the problem:
- Your operating system (Windows/Mac OS/Linux)
- Docker logs, especially of the `postgres` service. On Mac OS and Linux, you can get them with the command `docker-compose logs postgres`
- If you are using Mac OS or Linux, the output of the command `ls -l` in the directory that contains `start.sh`

It seems possible that the database isn't getting written to disk for some reason, and so the data is lost when it restarts.

**Comment by wxyhgk** [comment]
> Hello, thanks for reporting this issue. I will need some more information to figure out what could be the problem:
> 
> * Your operating system (Windows/Mac OS/Linux)
> * Docker logs, especially of the `postgres` service. On Mac OS and Linux, you can get them with the command `docker-compose logs postgres`
> * If you are using Mac OS or Linux, the output of the command `ls -l` in the directory that contains `start.sh`
> 
> It seems possible that the database isn't getting written to disk for some reason, and so the data is lost when it restarts.

I have solve this problem , I use `docker-compose up` or `docker-compose stop`  to solve this

**Comment by RaphaelRobidas** [comment]
Okay, I will close this issue then since it is resolved. Thank you for sharing your solution.
