### ISSUE TITLE
can not run orca

### ISSUE THREAD

**Issue by wxyhgk** [cyllab/CalcUS#18]
![image](https://user-images.githubusercontent.com/37659181/201033501-eb8f2629-6396-4228-9f47-6c9174275e90.png)

I have loaded the openmpi and orca environment variables,but can not run orca

**Comment by RaphaelRobidas** [comment]
I assume this is using a remote server using submission through SLURM. For ORCA, you will need to define the `EBROOTORCA` variable which corresponds to the ORCA folder (probably `/home/wxyhgk/calcus/calcus-orca` in your case). This is because ORCA needs to be called with its full path when running with more than one process.

Let me know if that fixes it!

**Comment by wxyhgk** [comment]
> 
As you said, I calculated by remote. ORCA has been installed in the calcus directory of my remote server, and my environment variable here is also in the calcus directory. I wonder why it cannot be started

**Comment by RaphaelRobidas** [comment]
So you define `EBROOTORCA` in your `.bashrc`? Because it is necessary and doesn't seem to be in your script above.

If so, do you have any log or error message that you can share to help me debug the issue?

**Comment by wxyhgk** [comment]
> So you define `EBROOTORCA` in your `.bashrc`? Because it is necessary and doesn't seem to be in your script above.
> 
> If so, do you have any log or error message that you can share to help me debug the issue?

I used to write the environment variables to `.bashrc`, but I found it didn't work, so I went that way, and then I used moule to load the environment variables, which didn't seem to work either.

I can confirm that my orca is running well locally.

**Comment by RaphaelRobidas** [comment]
If `EBROOTORCA` is not in your `.bashrc`, add `export EBROOTORCA=/home/wxyhgk/calcus/calcus-orca` to your submission script. It is not enough to have ORCA in `$PATH`, you also need `EBROOTORCA`.

**Comment by wxyhgk** [comment]
> So you define `EBROOTORCA` in your `.bashrc`? Because it is necessary and doesn't seem to be in your script above.
> 
> If so, do you have any log or error message that you can share to help me debug the issue?

Running locally, I loaded openmpi and orca by `module`. It works perfectly

![image](https://user-images.githubusercontent.com/37659181/201090175-bb2fbad2-f4b5-4c01-a3f6-930da6e4ed7e.png)

You can see that my environment variables are set correctly here

![image](https://user-images.githubusercontent.com/37659181/201090852-76963a15-6390-4d5c-bbd7-e79acb8b9e72.png)

**Comment by wxyhgk** [comment]
I have set up the environment variables in the `.bashrc` 

![image](https://user-images.githubusercontent.com/37659181/201093827-7f4c00bf-01cb-42a8-90be-14a00d979ed4.png)

And I use orca calculation, why does it use g16?
![image](https://user-images.githubusercontent.com/37659181/201094084-ea6394fb-493f-4903-8020-531f15b71d6d.png)

**Comment by RaphaelRobidas** [comment]
> > If `EBROOTORCA` is not in your `.bashrc`, add `export EBROOTORCA=/home/wxyhgk/calcus/calcus-orca` to your submission script. It is not enough to have ORCA in `$PATH`, you also need `EBROOTORCA`.
> 
> Ok, I'll try.But I have a question, `gaussian16` and `xtb` can run this way, why not `orca`?

ORCA needs to be called with its full path when running with more than one process. CalcUS will add the line `$EBROOTORCA/orca calc.inp` to your submission script, which will not work if `$EBROOTORCA` is not defined.


 > And I use orca calculation, why does it use g16?

This is strange. Perhaps you have launched remote calculations in the past, then deleted the local database and restarted from scratch? This would mean that CalcUS is using remote folders that already exist and already contain logs. You can delete all the remote folders in your remote scratch (most likely `/scratch/wxyhgk/calcus/`).

**Comment by wxyhgk** [comment]
> 
How about this?

![image](https://user-images.githubusercontent.com/37659181/201101873-9c3bd4d2-999d-4259-b91c-a1aa3e6e1f61.png)

**Comment by RaphaelRobidas** [comment]
This is because `$EBROOTORCA` is blank. There should be the full path to the ORCA directory (`$EBROOTORCA`) before the slash.

**Comment by wxyhgk** [comment]
> 这是因为是空白的。斜杠前应该有 ORCA 目录 （） 的完整路径。`$EBROOTORCA``$EBROOTORCA`

But I've already set the environment variables in the `.bashrc` file

**Comment by wxyhgk** [comment]
> This is because `$EBROOTORCA` is blank. There should be the full path to the ORCA directory (`$EBROOTORCA`) before the slash.

I have solve this ,pretty good

![image](https://user-images.githubusercontent.com/37659181/201116616-499326af-7942-4f98-93d7-424fe68c25d0.png)
