### ISSUE TITLE
2.0 bug: You may need to add 'ip' to ALLOWED_HOSTS.

### ISSUE THREAD

**Issue by wxyhgk** [cyllab/CalcUS#19]
<img width="994" alt="image" src="https://user-images.githubusercontent.com/37659181/201479432-bdac75f2-a015-4dd7-ab8a-c70c613e29f5.png">

**Comment by RaphaelRobidas** [comment]
You need to add the IP to `ALLOWED_HOSTS` in `calcus/settings.py`

**Comment by wxyhgk** [comment]
> 您需要将IP添加到`ALLOWED_HOSTS``calcus/settings.py`

Ok,I have do it

**Comment by wxyhgk** [comment]
> 您需要将IP添加到`ALLOWED_HOSTS``calcus/settings.py`
Error in version1 still exists and cannot be started from bash start.sh

<img width="928" alt="image" src="https://user-images.githubusercontent.com/37659181/201480106-a224c51f-8608-4717-9038-7176435f5c90.png">

**Comment by RaphaelRobidas** [comment]
Thanks for the report, I have pushed the change (fadd71ad41422f54883d5fb91992dadc514759c8) You will have to update your local `yml` file with `git pull`. Let me know if this solves your issue.

**Comment by wxyhgk** [comment]
> Thanks for the report, I have pushed the change ([fadd71a](https://github.com/cyllab/CalcUS/commit/fadd71ad41422f54883d5fb91992dadc514759c8)) You will have to update your local `yml` file with `git pull`. Let me know if this solves your issue.


It is also error

<img width="954" alt="image" src="https://user-images.githubusercontent.com/37659181/201481094-b5952cd1-c4cf-4293-ac8d-6c32f0915536.png">

**Comment by RaphaelRobidas** [comment]
Are you using the CalcUS 1 database or are you creating a new one? Unfortunately, it is not possible to migrate the database from version 1 to version 2. You need to start with a new database.

**Comment by wxyhgk** [comment]
> Are you using the CalcUS 1 database or are you creating a new one? Unfortunately, it is not possible to migrate the database from version 1 to version 2. You need to start with a new database.

Then I'll delete all the doeker projects first and try

**Comment by wxyhgk** [comment]
> Are you using the CalcUS 1 database or are you creating a new one? Unfortunately, it is not possible to migrate the database from version 1 to version 2. You need to start with a new database.

There still seems to be a problem, so let's leave it at that

**Comment by RaphaelRobidas** [comment]
What is the new error message?

**Comment by wxyhgk** [comment]
> What is the new error message?

I am a cloud server and can reinstall the system at any time. I make sure my system is clean. Using `bash start.sh` will give an error as shown in the figure

![image](https://user-images.githubusercontent.com/37659181/201654367-96a9761a-20a8-4437-aaf1-4998aeacf884.png)

**Comment by RaphaelRobidas** [comment]
Do you have the new version of `docker-compose.yml`? The `r` mode is removed in the new version, so you shouldn't have this issue. You can also try to remove the `:r` manually from the file as you did before to see if that solves the problem.

**Comment by wxyhgk** [comment]
> 你有新版本的 ？该模式在新版本中被删除，因此您不应该遇到此问题。您也可以尝试像以前一样手动从文件中删除，看看是否可以解决问题。`docker-compose.yml``r``:r`

Bugs about your program,You can improve it this way

# 1. 
![image](https://user-images.githubusercontent.com/37659181/201666340-bb03ea39-9a95-40cf-8f64-e2c89d166021.png)


# 2.

step1:
`cd data`    

step2:
`rm -rf postgresql.conf/` 

step3;
`vi postgresql.conf`

Fill in the code as shown below

```
listen_addresses = '*'
max_connections = 1000 # When launching many calculations, it is easy to run out of connections
shared_buffers = 128MB
dynamic_shared_memory_type = posix
max_wal_size = 1GB
min_wal_size = 80MB
log_timezone = 'Etc/UTC'
datestyle = 'iso, mdy'
timezone = 'Etc/UTC'
lc_messages = 'en_US.utf8'
lc_monetary = 'en_US.utf8'
lc_numeric = 'en_US.utf8'
lc_time = 'en_US.utf8'
default_text_search_config = 'pg_catalog.english'
```

**Comment by RaphaelRobidas** [comment]
Closing since this issue seems mostly resolved.
