### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by wxyhgk** [cyllab/CalcUS#20]
like this

![image](https://user-images.githubusercontent.com/37659181/201676252-c9276cc0-6a18-46c5-8ed9-d15cda6bd84e.png)

**Comment by RaphaelRobidas** [comment]
Seems to be the same error as in #19, add the host IP to `ALLOWED_HOSTS`. You can also add `*.*.*.*` to `ALLOWED_HOSTS` if the IP changes often.

**Comment by wxyhgk** [comment]
> Seems to be the same error as in #19, add the host IP to `ALLOWED_HOSTS`. You can also add `*.*.*.*` to `ALLOWED_HOSTS` if the IP changes often.

I have do this,but also error

**Comment by RaphaelRobidas** [comment]
Have you restarted the server?
