### ISSUE TITLE
Style the "Download Project" page

### ISSUE THREAD

**Issue by RaphaelRobidas** [cyllab/CalcUS#23]
**Is your improvement related to a problem? Please describe.**
The "Download Project" page (`/download_project/<project.id>`) is bland and looks empty:
![image](https://user-images.githubusercontent.com/52597883/216819181-066a9d78-dfe5-43b4-9c02-f8aaafa18742.png)

**Describe the solution or change you'd like**
The page could be improved to look better, while not necessarily having more elements for the moment. Any reasonable styling would be great, I don't have anything too specific in mind.

If you want to do more, some statistics about the project could be displayed next to the form. For example, a reminder of the project name and project author, the number of molecules in the project, possibly the total number of calculations in the project (calculated recursively for each molecule, ensemble and structure). This is not mandatory, but could add some more content on the page.

**Comment by Omkar0803** [comment]
I have made an UI for download project page. I have also added statistics section, will try to add that in the UI. So hows the design and should I start working on it?

**Comment by RaphaelRobidas** [comment]
That looks great! You should definitely make it and submit a PR

**Comment by Omkar0803** [comment]
UI portion is completed. From where can I get the statistics data?
![Uploading Screenshot from 2023-02-07 17-48-07.png…]()

**Comment by RaphaelRobidas** [comment]
Yes, you will have to generate the statistics in the `download_project` function of `frontend/views.py`, then pass them as parameters to the render function (like "proj" is currently being passed). Then, you can insert them in the HTML template with `{{ variable_name }}`.

The statistics can be generated by leveraging the existing [many-to-one relationships](https://docs.djangoproject.com/en/4.1/topics/db/examples/many_to_one/) between database objects, as defined in `frontend/models.py`.

**Comment by Omkar0803** [comment]
Hey @RaphaelRobidas, currently I am learning django framework, so can't contribute to backend part at this time. Should I make a PR for UI contribution ?

**Comment by RaphaelRobidas** [comment]
Sure, no problem!

**Comment by Omkar0803** [comment]
I have created a PR for UI improvement.
