### ISSUE TITLE
Cleaning all calculation orders should not remove "unseen" orders

### ISSUE THREAD

**Issue by RaphaelRobidas** [cyllab/CalcUS#31]
**Is your improvement related to a problem? Please describe.**
On the calculations page (`/calculations/`), there are buttons to "see" and "clean" calculation orders. When clicking on "Clean all completed" or "Clean all successful", calculation orders that recently completed could be cleaned before being seen by the user.

**Describe the solution or change you'd like**
When cleaning all calculation orders, the objects that are "unseen" (`order.last_seen_status != order.status`) should not be cleaned.

**Comment by RaphaelRobidas** [comment]
That is true, but it's a fragile approach. If a calculation changes status and the user does not refresh the page, the order will not appear as `new` and will be cleaned. The user will thus never see the "new" status of that order. The fix should also be in the backend, when a calculation is about to be "seen".

**Comment by anchalm03** [comment]
Hello @RaphaelRobidas !
This issue looks interesting to me, can you please assign me this?

**Comment by RaphaelRobidas** [comment]
@anchalm03 It would be better if you finished the other issue you worked on first

**Comment by anchalm03** [comment]
Yes, I am working on that too. I just wanted to take the issue because I figured out the backend part, and the functionality  is working fine. I am attaching the video here(all the edge cases covered).  This would be completely fixed if you could guide a little for the implementation on the frontend part.

https://user-images.githubusercontent.com/94220851/229367832-b5f16c64-6d60-43e2-9bfd-0a34d676265d.mp4

Thank You

**Comment by RaphaelRobidas** [comment]
@anchalm03 Oh, that's great then! For the frontend, you can look at the function  `see_all` in `frontend/templates/frontend/calculations.html` (lines 168-180). You should filter out the calculation orders (`article` elements) that have the class `new`, so that they don't get passed to the `_see` function.

**Comment by anchalm03** [comment]
I want to inform you that, the backend functionality worked when I did  `order.last_seen_status` != `0`  and not when `order.last_seen_status` != `order.status` .
I think the best way to do the frontend part, is to get the `last_seen_status` where we are setting the `new` tag and use the same condition in `clean_all_completed` and `clean_all_successful`. 
What do you think?

**Comment by RaphaelRobidas** [comment]
Sorry for the delay, I forgot to reply.

I'm not sure I understand what you're proposing. The condition `order.last_seen_status != order.status` is correct. For example, a running calculation (`status == 1`) can be either "seen" or "unseen". Your code seemed to work as expected, no? If you're stuck, you can create a draft PR and I will take a look at it.
