### ISSUE TITLE
Improving the web Front End [Google Summer of COde 2022]

### ISSUE THREAD

**Issue by ForchaGlen** [cyllab/CalcUS#4]
Hello Everyone!
Congratulations on being a selected organization for Google Summer of Code 2022.
 I would like to  contribute to open source by working on this issue **Improving the web frontend** .
- Please how may I start contributing.
- Please for the link to join the CalcUs developer group.

**Comment by RaphaelRobidas** [comment]
Hello, thanks for the interest!

Please send me an email: raphael dot robidas at usherbrooke dot com (remplacing the "dot" and "at" by the actual symbols). We can discuss further about your proposal for the project.

**Comment by RaphaelRobidas** [comment]
I just realized, I made a mistake in my email on the Open Chemistry wiki. The correct email is "raphael dot robidas at usherbrooke dot **ca**". Sorry for the confusion!
